import assert from "node:assert/strict";
import { createRequire } from "node:module";
const { chromium, expect } = createRequire(import.meta.url)("playwright/test");
const browser = await chromium.launch({ headless: true, channel: "msedge" });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on("pageerror", error => errors.push(error.message));
const button = name => page.getByRole("button", { name, exact: true });
const group = name => page.getByRole("group", { name, exact: true });
const table = page.getByTestId("delivery-status-table");
const legend = page.getByTestId("delivery-status-legend");
const query = async () => { await page.keyboard.press("Escape"); await button("查询").click(); };

try {
  await page.addInitScript(() => localStorage.setItem("mengchang_prototype_session", JSON.stringify({ username: "chaojiguanliyuan", mode: "user" })));
  await page.goto(process.env.BASE_URL || "http://localhost:3005/");
  await button("数据分析").click();
  await button("广告账户分析").click();
  await button("投放状态报表").click();
  await button("巨量千川").click();
  const start = page.getByLabel("计划搭建开始时间", { exact: true });
  const end = page.getByLabel("计划搭建结束时间", { exact: true });
  const defaultDates = [await start.inputValue(), await end.inputValue()];

  await button("部门筛选").click();
  for (const name of ["电商投放一部", "AIGC爆款内容拆解部"]) await group("部门").getByRole("checkbox", { name, exact: true }).check();
  await expect(table).toContainText("暂无数据");
  await query();
  await expect(table.locator("tbody tr")).toHaveCount(3);
  await expect(legend.locator(":scope > div")).toHaveCount(2);
  await button("清空部门").click();
  await expect(table.locator("tbody tr")).toHaveCount(3);
  await query();
  await expect(table).toContainText("暂无数据");

  await button("分组数据").click();
  await button("分组筛选").click();
  await group("部门").getByRole("button", { name: "电商投放一部", exact: true }).click();
  for (const name of ["女装千川放量组", "美妆珠宝爆款组"]) await group("分组").getByRole("checkbox", { name, exact: true }).check();
  await query();
  await expect(table.locator("tbody tr")).toHaveCount(3);
  await expect(legend.locator(":scope > div")).toHaveCount(2);

  await button("个人数据").click();
  await button("个人筛选").click();
  await group("部门").getByRole("button", { name: "电商投放一部", exact: true }).click();
  await group("分组").getByRole("button", { name: "女装千川放量组", exact: true }).click();
  await group("部门").getByRole("checkbox", { name: "电商投放一部", exact: true }).check();
  await group("个人").getByRole("checkbox", { name: "刘小青", exact: true }).uncheck();
  await expect(group("部门").getByRole("checkbox", { name: "电商投放一部", exact: true })).toHaveAttribute("aria-checked", "mixed");
  await expect(group("分组").getByRole("checkbox", { name: "女装千川放量组", exact: true })).toHaveAttribute("aria-checked", "mixed");
  await page.getByRole("searchbox", { name: "搜索个人", exact: true }).fill("徐振");
  await group("个人").getByRole("checkbox", { name: "徐振", exact: true }).check();
  await page.setViewportSize({ width: 390, height: 844 });
  const box = await page.getByRole("dialog").boundingBox();
  assert.ok(box && box.x >= 0 && box.y >= 0 && box.x + box.width <= 390 && box.y + box.height <= 844);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await query();
  await expect(table).toContainText("徐振");
  await expect(table).not.toContainText("刘小青");
  await button("收起").click();
  await expect(page.getByTestId("delivery-status-chart")).toHaveCount(0);
  await expect(table).toBeVisible();
  await button("展开").click();
  await expect(page.getByTestId("delivery-status-chart")).toBeVisible();

  await button("广告主明细数据").click();
  await button("分类筛选").click();
  await expect(group("一级分类")).toBeVisible();
  for (const checkbox of await group("一级分类").getByRole("checkbox").all()) if (await checkbox.isEnabled()) await checkbox.check();
  await query();
  await expect(table.locator("tbody tr").nth(1)).toBeVisible();
  const accountCount = await table.locator("tbody tr").count() - 1;
  await expect(legend.locator(":scope > div")).toHaveCount(accountCount);
  const accountId = await table.locator("tbody tr").nth(1).locator("td").first().locator("span").last().innerText();
  await page.getByLabel("广告账户 ID", { exact: true }).fill(accountId);
  await expect(table.locator("tbody tr")).toHaveCount(accountCount + 1);
  await query();
  await expect(table.locator("tbody tr")).toHaveCount(2);
  await start.fill("2050-01-01");
  await end.fill("2050-01-03");
  await query();
  await expect(table.locator("tbody tr").nth(1).locator("td").last()).toHaveText("0");
  await expect(legend.locator(":scope > div")).toHaveCount(1);
  await button("未投放").click();
  await expect(button("未投放")).toHaveAttribute("aria-pressed", "true");
  await button("列设置").click();
  await page.getByRole("dialog").getByRole("checkbox", { name: "已删除", exact: true }).uncheck();
  await expect(button("按已删除排序")).toHaveCount(0);
  await page.keyboard.press("Escape");
  await button("重置").click();
  await expect(start).toHaveValue(defaultDates[0]);
  await expect(end).toHaveValue(defaultDates[1]);
  await expect(table).toContainText("暂无数据");
  await expect(button("清空分类")).toHaveCount(0);
  await button("巨量广告").click();
  await expect(table).toContainText("暂无数据");
  assert.deepEqual(errors, []);
  console.log("Delivery cascades, query snapshots, account series, zero dates, reset, columns and narrow overlays passed");
} finally {
  await browser.close();
}
