import assert from "node:assert/strict";
import { createRequire } from "node:module";
const { chromium, expect } = createRequire(import.meta.url)("playwright/test");
const browser = await chromium.launch({ headless: true, channel: "msedge" });
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
page.setDefaultTimeout(15000);
const errors = [];
page.on("pageerror", error => errors.push(error.message));
const button = name => page.getByRole("button", { name, exact: true });
const dialog = name => page.getByRole("dialog", { name, exact: true });
const table = () => page.getByTestId("finished-derivations");
const row = n => page.locator(`[data-derivative-id="DER-fv1-DEMO-${n}"]`);
const open = async () => {
  await page.locator("#sidebar-item-resources").click();
  await page.getByText("0730-8835-鲁月园-复古耳环动态奢感视频.mp4", { exact: true }).click();
  await button("衍生视频").click();
};
const setRole = async (permissions, username = "staff") => page.evaluate(async ({ permissions, username }) => {
  localStorage.setItem("mengchang_prototype_session", JSON.stringify({ username, mode: "user" }));
  localStorage.setItem("cloud_video_roles_v2", JSON.stringify([{ id: "role_staff", enabled: true, checkedKeys: permissions }]));
  window.dispatchEvent(new Event("mengchang-ad-workflow-change"));
}, { permissions, username });
try {
  await page.addInitScript(() => localStorage.setItem("mengchang_prototype_session", JSON.stringify({ username: "chaojiguanliyuan", mode: "user" })));
  await page.goto(process.env.PREVIEW_URL || "http://localhost:3000/", { waitUntil: "domcontentloaded" });
  await open();
  await expect(table().locator("tbody tr")).toHaveCount(8);
  await expect(table()).not.toContainText("衍生方式");
  await expect(table().getByLabel("操作人").locator("option")).toHaveCount(4);
  await table().scrollIntoViewIfNeeded();
  await page.screenshot({ path: "tmp/finished-derivations-desktop.png" });
  await expect(row(3).getByRole("button", { name: /^编辑备注/ })).toBeVisible();
  await row(3).getByRole("button", { name: /^编辑备注/ }).click();
  await page.getByLabel("记录备注").fill("不保存的内容");
  await dialog("填写备注").getByRole("button", { name: "取消", exact: true }).click();
  await expect(row(3)).not.toContainText("不保存的内容");
  await row(3).getByRole("button", { name: /^编辑备注/ }).click();
  await page.getByLabel("记录备注").fill("产品特写, 复投测试");
  await dialog("填写备注").getByRole("button", { name: "确定", exact: true }).click();
  await expect(row(3)).toContainText("产品特写, 复投测试");
  await row(2).getByRole("button", { name: /^编辑备注/ }).click();
  await page.getByLabel("记录备注").fill("");
  await dialog("填写备注").getByRole("button", { name: "复投测试", exact: true }).click();
  await dialog("填写备注").getByRole("button", { name: "产品特写", exact: true }).click();
  await expect(page.getByLabel("记录备注")).toHaveValue("复投测试, 产品特写");
  await page.screenshot({ path: "tmp/finished-derivations-note.png" });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "tmp/finished-derivations-note-mobile.png" });
  assert.ok(await dialog("填写备注").evaluate(el => el.scrollWidth <= el.clientWidth));
  await dialog("填写备注").getByRole("button", { name: "确定", exact: true }).click();
  await page.setViewportSize({ width: 1920, height: 1080 });
  await table().getByLabel("请输入备注关键词").fill("复投测试");
  await expect(table().locator("tbody tr")).toHaveCount(2);
  await table().getByLabel("请输入备注关键词").fill("");
  await table().getByLabel("衍生状态", { exact: true }).selectOption("成功");
  await expect(table().locator("tbody tr")).toHaveCount(3);
  await table().getByLabel("衍生状态", { exact: true }).selectOption("");
  await table().getByLabel("请输入素材ID").fill("QC-fv1-260922-1");
  await expect(table().locator("tbody tr")).toHaveCount(1);
  await table().getByLabel("请输入素材ID").fill("不存在");
  await expect(table().getByText("暂无数据", { exact: true })).toBeVisible();
  await table().getByLabel("请输入素材ID").fill("");
  const owner = await row(2).locator("td").nth(5).innerText();
  await table().getByLabel("操作人").selectOption({ label: owner });
  assert.ok(await table().locator("tbody tr").count() >= 2);
  await table().getByLabel("操作人").selectOption("");
  await row(1).getByRole("checkbox").check();
  await row(4).getByRole("checkbox").check();
  await expect(table().getByRole("button", { name: "批量删除", exact: true })).toBeDisabled();
  await row(4).getByRole("checkbox").uncheck();
  await expect(table().getByRole("button", { name: "批量删除", exact: true })).toBeEnabled();
  await row(1).getByRole("checkbox").uncheck();
  const download = page.waitForEvent("download");
  await row(1).getByRole("button", { name: "下载", exact: true }).click();
  await download;
  // Colliding titles must not confuse the ID-based analytics target.
  await page.evaluate(async () => {
    const moduleUrl = performance.getEntriesByType("resource").find(entry => new URL(entry.name).pathname === "/src/lib/videoDerivation.ts")?.name || "/src/lib/videoDerivation.ts";
    const { getDerivationRecords, changeDerivations } = await import(moduleUrl);
    const records = getDerivationRecords();
    records.find(r => r.id === "DER-fv1-DEMO-2").name = records.find(r => r.id === "DER-fv1-DEMO-1").name;
    changeDerivations(["DER-fv1-DEMO-2"], "chaojiguanliyuan", "note", "复投测试", "fv1");
  });
  await row(2).getByRole("button", { name: "查看数据", exact: true }).click();
  const target = page.locator('[data-highlighted="true"]');
  await expect(target).toHaveAttribute("data-video-id", "DER-fv1-DEMO-2");
  await expect(button("明细")).toBeVisible();
  await expect(target).toBeInViewport();
  await page.screenshot({ path: "tmp/finished-derivations-analytics.png" });
  await target.getByRole("button", { name: "预览", exact: true }).click();
  await expect(page.locator('[role="dialog"] video')).toBeVisible();
  await expect.poll(() => page.locator('[role="dialog"] video').evaluate(v => v.readyState)).toBeGreaterThan(1);
  await page.locator('[role="dialog"]').getByRole("button", { name: /^关闭/ }).click();
  await open();
  await row(3).getByRole("button", { name: "查看数据", exact: true }).click();
  await expect(target).toHaveAttribute("data-video-id", "DER-fv1-DEMO-3");
  await expect(page.getByText("该衍生视频暂无投放数据", { exact: true })).toBeVisible();
  await expect(target).toBeInViewport();
  await setRole([]);
  await expect(page.locator("tr[data-video-id]")).toHaveCount(0);
  await expect(target).toHaveCount(0);
  await setRole([], "chaojiguanliyuan");
  await expect(target).toHaveAttribute("data-video-id", "DER-fv1-DEMO-3");
  await page.locator("#sidebar-item-ad_delivery").click();
  await expect(target).toHaveCount(0);
  await open();
  for (const width of [1440, 768, 390]) {
    await page.setViewportSize({ width, height: 1000 });
    if (width === 390) {
      await page.locator("aside button").last().click();
      await expect.poll(() => page.locator("aside").evaluate(el => el.getBoundingClientRect().width)).toBeLessThanOrEqual(65);
    }
    await table().scrollIntoViewIfNeeded();
    assert.ok(await table().evaluate(el => el.scrollWidth <= el.clientWidth));
    await page.screenshot({ path: `tmp/finished-derivations-${width}.png` });
  }
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.locator("aside button").last().click();
  await row(6).getByRole("button", { name: "重试", exact: true }).click();
  await dialog("重试衍生").getByRole("button", { name: "确定", exact: true }).click();
  await expect(row(6).getByText("成功", { exact: true })).toBeVisible({ timeout: 10000 });
  await row(4).getByRole("button", { name: "取消", exact: true }).click();
  await dialog("取消衍生").getByRole("button", { name: "确定", exact: true }).click();
  await expect(row(4)).toContainText("取消衍生");
  await row(6).getByRole("button", { name: "删除", exact: true }).click();
  await dialog("删除衍生视频").getByRole("button", { name: "确定", exact: true }).click();
  await expect(row(6)).toContainText("已删除");
  await row(1).getByRole("button", { name: /^编辑备注/ }).click();
  await setRole(["uc_ad_push", "uc_finished_derive", "uc_finished_derive_push"]);
  await expect(button("衍生视频")).toBeVisible();
  await expect(page.getByTestId("derivation-no-access")).toBeVisible();
  await expect(table()).toHaveCount(0);
  await expect(dialog("填写备注")).toHaveCount(0);
  await button("更多").click();
  await expect(button("衍生新视频")).toHaveCount(0);
  await expect(button("衍生视频并推送")).toHaveCount(0);
  await button("更多").click();
  await setRole(["uc_derivation"]);
  await expect(table().locator("tbody tr")).toHaveCount(8);
  await row(1).getByRole("button", { name: "推送", exact: true }).click();
  await expect(page.getByTestId("ad-derivation-options")).toHaveCount(0);
  await button("全部账户").click();
  await page.getByRole("checkbox", { name: "梦畅美妆旗舰店-千川主账户", exact: true }).check();
  await dialog("添加推送任务").getByRole("button", { name: "确定", exact: true }).click();
  await expect(table().getByText("已提交 1 条推送记录", { exact: true })).toBeVisible();
  await page.locator("#sidebar-item-operation_records").click();
  await expect(page.getByTestId("derivation-history").locator("tbody tr")).toHaveCount(6);
  await expect(page.getByTestId("derivation-history")).not.toContainText("复投测试");
  await setRole([]);
  await expect(page.getByRole("tab", { name: "衍生视频记录", exact: true })).toBeVisible();
  await expect(page.getByTestId("derivation-history")).toHaveCount(0);
  await expect(page.getByText("暂无衍生视频查看权限", { exact: true })).toBeVisible();
  assert.deepEqual(errors, []);
  console.log("PASS finished derivatives: all-member source scope, filters, persistent note edit/history, permissions, mixed batches, download/push, retry/cancel/delete, ID-based analytics navigation, preview and responsive overlays");
} catch (error) { await page.screenshot({ path: "tmp/finished-derivations-failure.png" }); throw error; }
finally { await browser.close(); }
