import assert from "node:assert/strict";
import { createRequire } from "node:module";
const { chromium, expect } = createRequire(import.meta.url)("playwright/test");
const browser = await chromium.launch({ headless: true, channel: "msedge" });
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
page.setDefaultTimeout(15000);
const errors = [];
page.on("pageerror", error => errors.push(error.message));
const panel = page.getByTestId("referenced-videos-produced");
const cards = panel.locator("[data-reference-id]");
const spend = panel.getByTestId("reference-metric-1").locator("span").first();
const button = name => page.getByRole("button", { name, exact: true });
const selectDimension = async name => {
  await button("人员筛选维度").click();
  await button(name).click();
};
const selectEntity = async (kind, name) => {
  await button(`选择${kind}`).click();
  await page.getByLabel(`搜索${kind}`, { exact: true }).fill(name);
  await page.locator(`[aria-label="${kind}选项"]`).getByRole("button", { name: new RegExp(`^${name}`) }).click();
};
try {
  await page.addInitScript(() => localStorage.setItem("mengchang_prototype_session", JSON.stringify({ username: "chaojiguanliyuan", mode: "user" })));
  await page.goto(process.env.PREVIEW_URL || "http://localhost:3000/", { waitUntil: "domcontentloaded" });
  await page.locator("#sidebar-item-resources").click();
  await page.getByText("0730-8835-鲁月园-复古耳环动态奢感视频.mp4", { exact: true }).click();
  await button("被引用后出片").click();
  await expect(cards).toHaveCount(3);
  await expect(button("人员筛选维度")).toHaveText("作者");
  const initialSpend = await spend.textContent();
  assert.notEqual(initialSpend, "¥0.00");
  const today = await panel.getByLabel("消耗时间结束日期", { exact: true }).inputValue();
  await panel.scrollIntoViewIfNeeded();
  for (const [name, text] of [["人员筛选", "团队作者、分组筛选数据统计与下方视频列表"], ["上传时间", "上传时间筛选数据统计与下方视频列表"], ["消耗时间", "消耗时间仅筛选数据统计，不影响下方的视频列表"]]) {
    await button(`${name}说明`).hover();
    await expect(page.getByRole("tooltip", { name: text, exact: true })).toHaveText(text);
    await page.screenshot({ path: `tmp/reference-help-${name}.png` });
    await page.mouse.move(5, 5);
    await expect(page.getByRole("tooltip", { name: text, exact: true })).toHaveCount(0);
  }
  await button("人员筛选维度").click();
  await expect(page.locator('[aria-label="人员筛选维度选项"]').getByRole("button")).toHaveText(["团队", "分组", "作者"]);
  await page.screenshot({ path: "tmp/reference-dimension-desktop.png" });
  await page.keyboard.press("Escape");
  await expect(button("人员筛选维度")).toBeFocused();
  await button("选择作者").click();
  await expect(page.getByLabel("搜索作者", { exact: true })).toBeFocused();
  await page.getByLabel("搜索作者", { exact: true }).fill("不存在的成员");
  await expect(page.getByRole("status")).toHaveText("暂无匹配作者");
  await page.keyboard.press("Escape");
  await selectEntity("作者", "周雅");
  await expect(cards).toHaveCount(1);
  await expect(cards.first()).toContainText("周雅");
  await expect(spend).not.toHaveText(initialSpend);
  await selectDimension("团队");
  await expect(cards).toHaveCount(3);
  await selectEntity("团队", "电商投放一部");
  await expect(cards).toHaveCount(2);
  await selectDimension("分组");
  await selectEntity("分组", "美妆珠宝爆款组");
  await expect(cards).toHaveCount(1);
  await button("清除人员筛选").click();
  await expect(cards).toHaveCount(3);
  await panel.getByLabel("引用成片排序").selectOption("按消耗金额排序");
  assert.equal(await cards.first().getAttribute("data-reference-id"), "dv2");
  const snapshot = await cards.allTextContents();
  await panel.getByLabel("消耗时间开始日期", { exact: true }).fill("2000-01-01");
  await panel.getByLabel("消耗时间结束日期", { exact: true }).fill("2000-01-02");
  await expect(spend).toHaveText("¥0.00");
  assert.deepEqual(await cards.allTextContents(), snapshot);
  await panel.getByLabel("消耗时间开始日期", { exact: true }).fill("2030-01-01");
  await expect(panel.getByRole("alert")).toHaveText("消耗时间的开始日期不能晚于结束日期");
  await expect(spend).toHaveText("¥0.00");
  assert.deepEqual(await cards.allTextContents(), snapshot);
  await panel.getByLabel("消耗时间开始日期", { exact: true }).fill("");
  await panel.getByLabel("消耗时间结束日期", { exact: true }).fill("");
  await expect(spend).toHaveText("¥5,620.00");
  await expect(panel.getByRole("alert")).toHaveCount(0);
  const firstUpload = await cards.nth(1).getByTestId("reference-upload-date").textContent();
  await panel.getByLabel("上传时间开始日期", { exact: true }).fill(firstUpload);
  await expect(cards).toHaveCount(1);
  await expect(spend).toHaveText("¥1,280.00");
  await panel.getByLabel("上传时间结束日期", { exact: true }).fill("2000-01-01");
  await expect(panel.getByRole("alert")).toContainText("上传时间");
  await expect(cards).toHaveCount(1);
  await panel.getByLabel("上传时间结束日期", { exact: true }).fill("");
  await panel.getByLabel("上传时间开始日期", { exact: true }).fill("2040-01-01");
  await expect(cards).toHaveCount(0);
  await expect(panel.getByRole("status")).toHaveText("暂无符合条件的成片");
  await expect(spend).toHaveText("¥0.00");
  await panel.getByLabel("上传时间开始日期", { exact: true }).fill("");
  await expect(cards).toHaveCount(3);
  await selectDimension("团队");
  await selectEntity("团队", "电商投放一部");
  await page.evaluate(async () => {
    const { readReportOrganization } = await import("/src/lib/analyticsOrganization.ts");
    const depts = readReportOrganization().depts;
    depts.find(node => node.id === "dept_1").name = "电商投放一部-更新";
    localStorage.setItem("cloud_video_depts", JSON.stringify(depts));
    window.dispatchEvent(new Event("mengchang-organization-change"));
  });
  await expect(button("选择团队")).toHaveText("电商投放一部-更新");
  await expect(cards).toHaveCount(2);
  await button("清除人员筛选").click();
  await selectDimension("作者");
  await panel.getByLabel("消耗时间结束日期", { exact: true }).fill(today);
  await panel.getByLabel("引用成片排序").selectOption("按关联时间排序");
  await page.screenshot({ path: "tmp/reference-filters-desktop.png" });
  for (const width of [1366, 768]) {
    await page.setViewportSize({ width, height: 900 });
    await button("人员筛选维度").scrollIntoViewIfNeeded();
    await button("选择作者").click();
    const popover = page.locator('[data-overlay-layer="popover"]').last();
    const box = await popover.boundingBox();
    assert.ok(box.x >= 0 && box.x + box.width <= width && box.y >= 0 && box.y + box.height <= 900);
    await page.screenshot({ path: `tmp/reference-filters-${width}.png` });
    await page.keyboard.press("Escape");
    assert.equal(await panel.evaluate(el => el.scrollWidth <= el.clientWidth), true);
  }
  assert.deepEqual(errors, []);
  console.log("PASS: screenshot tooltips, admin-backed scopes, search/reset, list+metrics filters, spend-only metrics, invalid/empty dates, sorting and popover bounds");
} catch (error) {
  await page.screenshot({ path: "tmp/reference-filters-failure.png" });
  throw error;
} finally { await browser.close(); }
