import assert from "node:assert/strict";
import { createRequire } from "node:module";
const { chromium, expect } = createRequire(import.meta.url)("playwright/test");
const browser = await chromium.launch({ headless: true, channel: "msedge" });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
page.setDefaultTimeout(15000);
const errors = [];
page.on("pageerror", error => errors.push(error.message));
const button = name => page.getByRole("button", { name, exact: true });
const platform = button("互动数据平台");
const scope = button("互动数据范围");
const menu = () => page.getByRole("listbox", { name: /互动数据.*选项/ });
const panel = page.getByTestId("video-interaction-panel");
const stableCurve = async () => {
  let previous;
  await expect.poll(async () => {
    const current = await page.locator(".recharts-area-curve").first().getAttribute("d");
    const stable = !!current && current === previous;
    previous = current;
    return stable;
  }, { intervals: [200] }).toBe(true);
  return previous;
};
const bounds = async () => {
  const box = await menu().locator("..").boundingBox();
  const viewport = page.viewportSize();
  assert.ok(box.x >= 0 && box.y >= 0 && box.x + box.width <= viewport.width && box.y + box.height <= viewport.height, JSON.stringify(box));
  assert.equal(await menu().evaluate(el => el.scrollWidth <= el.clientWidth), true);
};
try {
  await page.addInitScript(() => localStorage.setItem("mengchang_prototype_session", JSON.stringify({ username: "chaojiguanliyuan", mode: "user" })));
  await page.goto(process.env.PREVIEW_URL || "http://localhost:3000/", { waitUntil: "domcontentloaded" });
  await page.locator("#sidebar-item-resources").click();
  await page.getByText("0730-8835-鲁月园-复古耳环动态奢感视频.mp4", { exact: true }).click();
  await button("互动数据").click();
  await expect(platform).toHaveText("全域直播");
  await expect(scope).toHaveText("全部抖音互动数据");
  await expect(panel).not.toContainText("官方开放API");
  const beforeSize = await scope.boundingBox();
  const chart = page.locator(".recharts-area-curve").first();
  await expect(chart).toBeVisible();
  await stableCurve();
  await platform.click();
  await expect(menu().getByRole("option")).toHaveText(["全域直播-千川", "全域商品-千川", "标准-千川", "腾讯ADQ", "TikTok"]);
  await expect(menu().getByRole("option", { name: "全域直播-千川", exact: true })).toBeFocused();
  await bounds();
  await page.screenshot({ path: "tmp/video-interaction-platform.png" });
  await page.keyboard.press("ArrowDown");
  await page.keyboard.press("Enter");
  await expect(platform).toHaveText("全域商品");
  await expect(platform).toBeFocused();
  await stableCurve();
  const chartSurface = page.locator(".recharts-surface").first();
  const aggregateAxis = await chartSurface.textContent();
  assert.ok(aggregateAxis.includes("0s"));
  await scope.click();
  const options = menu().getByRole("option");
  assert.ok(await options.count() >= 5);
  await expect(options.nth(1)).toContainText("账户：");
  await expect(options.nth(1)).toContainText("素材：0730-8835-鲁月园-复古耳环动态奢感视频");
  await expect(options.nth(1)).toContainText("消耗：");
  assert.equal(await menu().locator("..").evaluate(el => el.scrollHeight > el.clientHeight), true);
  await bounds();
  await page.screenshot({ path: "tmp/video-interaction-scope.png" });
  await options.nth(2).click();
  await expect(scope).toContainText("转码");
  assert.equal((await scope.boundingBox()).width, beforeSize.width);
  await expect(chart).toBeVisible();
  await stableCurve();
  await expect(chartSurface).not.toHaveText(aggregateAxis);
  await scope.click();
  await expect(menu().getByRole("option", { selected: true })).toContainText("转码");
  await page.keyboard.press("Escape");
  await expect(menu()).toHaveCount(0);
  await expect(scope).toBeFocused();
  await scope.click();
  await button("互动数据").click();
  await expect(menu()).toHaveCount(0);
  await button("添加帧复盘").click();
  await button("取消").click();
  for (const [label, text] of [["腾讯ADQ", "全部腾讯互动数据"], ["TikTok", "全部TikTok互动数据"], ["标准-千川", "全部抖音互动数据"], ["全域直播-千川", "全部抖音互动数据"]]) {
    await platform.click();
    await menu().getByRole("option", { name: label, exact: true }).click();
    await expect(scope).toHaveText(text);
    await scope.click();
    if (label === "腾讯ADQ" || label === "TikTok") {
      await expect(menu().getByRole("status")).toHaveText("暂无互动数据");
      await expect(page.locator(".recharts-area-curve")).toHaveCount(0);
      await expect(panel.locator(".recharts-wrapper")).toHaveCount(0);
      await expect(page.getByTestId("video-interaction-empty")).toHaveText("暂无数据");
      await expect(panel).not.toContainText("官方开放API");
    }
    await page.keyboard.press("Escape");
  }
  await stableCurve();
  await page.screenshot({ path: "tmp/video-interaction-desktop.png" });
  await button("返回成片列表").click();
  await page.getByText("0730-8836-水光针去黄测评-爆款对比.mp4", { exact: true }).click();
  await button("互动数据").click();
  const empty = page.getByTestId("video-interaction-empty");
  await expect(empty).toHaveText("暂无数据");
  await expect.poll(() => empty.locator("img").evaluate(img => img.complete && img.naturalWidth === 280)).toBe(true);
  await expect(panel.locator(".recharts-wrapper")).toHaveCount(0);
  await expect(panel).toContainText("根据巨量接口实时查询");
  await expect(panel).not.toContainText("官方开放API");
  await panel.screenshot({ path: "tmp/video-interaction-empty-desktop.png" });
  await page.setViewportSize({ width: 1024, height: 844 });
  await empty.scrollIntoViewIfNeeded();
  assert.equal(await empty.evaluate(el => el.scrollWidth <= el.clientWidth), true);
  await page.screenshot({ path: "tmp/video-interaction-empty-1024.png" });
  await page.setViewportSize({ width: 1600, height: 1000 });
  await platform.click();
  await menu().getByRole("option", { name: "全域商品-千川", exact: true }).click();
  await expect(empty).toHaveCount(0);
  await stableCurve();
  await scope.click();
  assert.ok(await menu().getByRole("option").count() >= 5);
  await expect(menu()).not.toContainText("消耗：0.00");
  await expect(menu()).toContainText("水光针去黄测评-爆款对比");
  await page.screenshot({ path: "tmp/video-interaction-product-examples.png" });
  await menu().getByRole("option").nth(1).click();
  await stableCurve();
  await expect(scope).toContainText("原片");
  for (const width of [1024, 390]) {
    await page.setViewportSize({ width, height: 844 });
    await scope.click();
    await bounds();
    await page.screenshot({ path: `tmp/video-interaction-${width}.png` });
    await page.keyboard.press("End");
    await page.keyboard.press("Enter");
    await expect(scope).toContainText("转码");
    await platform.click();
    await bounds();
    await page.keyboard.press("Escape");
    await expect(platform).toBeFocused();
  }
  assert.deepEqual(errors, []);
  console.log("PASS: five channels, scoped records, selection/reset, empty state, keyboard/outside click, stable trigger size and desktop/mobile popover bounds");
} catch (error) {
  await page.screenshot({ path: "tmp/video-interaction-failure.png" });
  throw error;
} finally { await browser.close(); }
